[package]
authors = ["Michael-F-Bryan <michaelfbryan@gmail.com>"]
name = "include_dir"
version = "0.1.0"

[dependencies]
error-chain = "0.10.0"
walkdir = "1.0.7"

[dev-dependencies]
tempfile = "2.1.5"
