[package]
name = "include_dir_impl"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
description = "Implementation crate for include_dir"

[dependencies]
proc-macro-hack = "0.4"
syn = "0.14.1"
include_dir_core = { path = "../include_dir_core" }
quote = "0.6.3"

[lib]
proc-macro = true
