[package]
name = "include_dir"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]

[dependencies]
include_dir_impl = { path = "../include_dir_impl" }
include_dir_core = { path = "../include_dir_core" }
proc-macro-hack = "0.4"
