[package]
name = "include_dir"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]

[dependencies]
include_dir_impl = { path = "../include_dir_impl" }
proc-macro-hack = "0.4"
failure = "0.1.1"
quote = "0.6.3"
proc-macro2 = "0.4.4"
