[package]
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
name = "include_dir"
version = "0.2.1"
description = "Embed the contents of a directory in your binary"
license = "MIT"
readme = "../README.md"
keywords = ["assets", "include", "embed", "dir"]
repository = "https://github.com/Michael-F-Bryan/include_dir"
categories = ["development-tools", "web-programming", "game-engines"]

[badges.appveyor]
branch = "master"
repository = "Michael-F-Bryan/include-dir"
service = "github"

[badges.travis-ci]
branch = "master"
repository = "Michael-F-Bryan/include_dir"

[dependencies]
glob = "0.2.11"
proc-macro-hack = "0.4"

[dependencies.include_dir_impl]
#version = "0.2.1"
path = "../include_dir_impl"

[features]
default = []
example-output = []

[dev-dependencies]
tempfile = "3.1.0"

[package.metadata.docs.rs]
all-features = true
